export const normalizedResults = [
  {
    description:
      '<div><img class="emoji" title=":atom:" alt=":atom:" src="https://github.githubassets.com/images/icons/emoji/atom.png" height="20" width="20" align="absmiddle"> The hackable text editor</div>',
    id: "MDEwOlJlcG9zaXRvcnkzMjI4NTA1",
    license: "MIT license",
    name: "atom",
    owner: "atom",
    stars: 58554,
    url: "https://github.com/atom/atom",
  },
  {
    description:
      "<div>The Atomic Game Engine is a multi-platform 2D and 3D engine with a consistent API in C++, C#, JavaScript, and TypeScript</div>",
    id: "MDEwOlJlcG9zaXRvcnkyOTc5MDcwNw==",
    license: "OTHER license",
    name: "AtomicGameEngine",
    owner: "AtomicGameEngine",
    stars: 2764,
    url: "https://github.com/AtomicGameEngine/AtomicGameEngine",
  },
  {
    description: "<div>Java course materials</div>",
    id: "MDEwOlJlcG9zaXRvcnk2ODY0Mzk3MQ==",
    license: "MIT license",
    name: "atom",
    owner: "rybalkinsd",
    stars: 307,
    url: "https://github.com/rybalkinsd/atom",
  },
  {
    description:
      "<div>Small and highly portable detection tests based on MITRE's ATT&amp;CK.</div>",
    id: "MDEwOlJlcG9zaXRvcnkxMDY1ODYxMjQ=",
    license: "MIT license",
    name: "atomic-red-team",
    owner: "redcanaryco",
    stars: 6584,
    url: "https://github.com/redcanaryco/atomic-red-team",
  },
  {
    description:
      "<div>Atom file-specific icons for improved visual grepping.</div>",
    id: "MDEwOlJlcG9zaXRvcnkxODE1NjIxMA==",
    license: "MIT license",
    name: "atom",
    owner: "file-icons",
    stars: 1238,
    url: "https://github.com/file-icons/atom",
  },
  {
    description:
      "<div>A reactive Java framework for building fault-tolerant distributed systems</div>",
    id: "MDEwOlJlcG9zaXRvcnkxNjI5NDkyMA==",
    license: "APACHE-2.0 license",
    name: "atomix",
    owner: "atomix",
    stars: 2250,
    url: "https://github.com/atomix/atomix",
  },
  {
    description:
      '<div><g-emoji class="g-emoji" alias="book" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4d6.png">📖</g-emoji> Documentation for Atom, generated by nanoc, hosted by GitHub Pages</div>',
    id: "MDEwOlJlcG9zaXRvcnkyNTAwMzA3MA==",
    license: "OTHER license",
    name: "flight-manual.atom.io",
    owner: "atom",
    stars: 607,
    url: "https://github.com/atom/flight-manual.atom.io",
  },
  {
    description:
      '<div><g-emoji class="g-emoji" alias="memo" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4dd.png">📝</g-emoji> Markdown preview in Atom</div>',
    id: "MDEwOlJlcG9zaXRvcnkxMjA4NzU3NQ==",
    license: "MIT license",
    name: "markdown-preview",
    owner: "atom",
    stars: 1235,
    url: "https://github.com/atom/markdown-preview",
  },
  {
    description: "<div>Atom Package Manager</div>",
    id: "MDEwOlJlcG9zaXRvcnk5OTE2Mzc5",
    license: "MIT license",
    name: "apm",
    owner: "atom",
    stars: 1258,
    url: "https://github.com/atom/apm",
  },
  {
    description:
      '<div><g-emoji class="g-emoji" alias="mega" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f4e3.png">📣</g-emoji> Help Wanted - Looking for Maintainer: <a href="https://github.com/Glavin001/atom-beautify/issues/2572">https://github.com/Glavin001/atom-beautify/issues/2572</a> | <g-emoji class="g-emoji" alias="lipstick" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/1f484.png">💄</g-emoji> Universal beautification package for Atom editor (<g-emoji class="g-emoji" alias="warning" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/26a0.png">⚠️</g-emoji> Currently migrating to <a href="https://github.com/Unibeautify/">https://github.com/Unibeautify/</a> and have very limited bandwidth for Atom-Beautify Issues. Thank you for your patience and understanding <g-emoji class="g-emoji" alias="heart" fallback-src="https://github.githubassets.com/images/icons/emoji/unicode/2764.png">❤️</g-emoji> )</div>',
    id: "MDEwOlJlcG9zaXRvcnkxNzM1NjkxMQ==",
    license: "MIT license",
    name: "atom-beautify",
    owner: "Glavin001",
    stars: 1507,
    url: "https://github.com/Glavin001/atom-beautify",
  },
];
