export const data = {
  nodes: [
    {
      description: ":atom: The hackable text editor",
      id: "MDEwOlJlcG9zaXRvcnkzMjI4NTA1",
      licenseInfo: {
        name: "MIT License",
        __typename: "License",
      },
      name: "atom",
      stargazerCount: 58550,
      url: "https://github.com/atom/atom",
      __typename: "Repository",
    },
    {
      description:
        "Share your workspace with team members and collaborate on code in real time in Atom",
      id: "MDEwOlJlcG9zaXRvcnk5MzUwMDAzMw==",
      licenseInfo: {
        name: "MIT License",
        __typename: "License",
      },
      name: "teletype",
      stargazerCount: 2383,
      url: "https://github.com/atom/teletype",
      __typename: "Repository",
    },
    {
      description: "Next generation vim support for atom",
      id: "MDEwOlJlcG9zaXRvcnkxMTgyNzEwNA==",
      licenseInfo: {
        name: "MIT License",
        __typename: "License",
      },
      name: "vim-mode",
      stargazerCount: 1719,
      url: "https://github.com/atom/vim-mode",
      __typename: "Repository",
    },
    {
      description: "Native Password Node Module",
      id: "MDEwOlJlcG9zaXRvcnk5NjgyODM0",
      licenseInfo: {
        name: "MIT License",
        __typename: "License",
      },
      name: "node-keytar",
      stargazerCount: 1325,
      url: "https://github.com/atom/node-keytar",
      __typename: "Repository",
    },
    {
      description: "Atom Package Manager",
      id: "MDEwOlJlcG9zaXRvcnk5OTE2Mzc5",
      licenseInfo: {
        name: "MIT License",
        __typename: "License",
      },
      name: "apm",
      stargazerCount: 1258,
      url: "https://github.com/atom/apm",
      __typename: "Repository",
    },
    {
      description: "📝 Markdown preview in Atom",
      id: "MDEwOlJlcG9zaXRvcnkxMjA4NzU3NQ==",
      licenseInfo: {
        name: "MIT License",
        __typename: "License",
      },
      name: "markdown-preview",
      stargazerCount: 1235,
      url: "https://github.com/atom/markdown-preview",
      __typename: "Repository",
    },
    {
      description: ":octocat: Git and GitHub integration for Atom",
      id: "MDEwOlJlcG9zaXRvcnk0NjE1NTc4Ng==",
      licenseInfo: {
        name: "MIT License",
        __typename: "License",
      },
      name: "github",
      stargazerCount: 1048,
      url: "https://github.com/atom/github",
      __typename: "Repository",
    },
    {
      description:
        "View and insert possible completions in the editor while typing",
      id: "MDEwOlJlcG9zaXRvcnkxNzI1NDcyOA==",
      licenseInfo: {
        name: "MIT License",
        __typename: "License",
      },
      name: "autocomplete-plus",
      stargazerCount: 965,
      url: "https://github.com/atom/autocomplete-plus",
      __typename: "Repository",
    },
    {
      description:
        "String-wise sequence CRDT powering peer-to-peer collaborative editing in Teletype for Atom.",
      id: "MDEwOlJlcG9zaXRvcnk5MTU5NzA1Ng==",
      licenseInfo: {
        name: "MIT License",
        __typename: "License",
      },
      name: "teletype-crdt",
      stargazerCount: 726,
      url: "https://github.com/atom/teletype-crdt",
      __typename: "Repository",
    },
    {
      description:
        "📖 Documentation for Atom, generated by nanoc, hosted by GitHub Pages",
      id: "MDEwOlJlcG9zaXRvcnkyNTAwMzA3MA==",
      licenseInfo: {
        name: "Other",
        __typename: "License",
      },
      name: "flight-manual.atom.io",
      stargazerCount: 608,
      url: "https://github.com/atom/flight-manual.atom.io",
      __typename: "Repository",
    },
  ],
  repositoryCount: 221,
  __typename: "SearchResultItemConnection",
};
